### ISSUE TITLE
ECDSA certificates

### ISSUE THREAD

**Issue by pekapl** [yourivw/LEClient#1]
Hi,

first of all - thanks for sharing this library on github, it's the best implementation of ACME in php I have seen so far and I'm planning to use it on production (with few modifications - hopefully they can be accepted into upstream).

I've added support for EC key generation in my fork (pekapl/LEClient) and if it's okay with you I will open pull request. 

My changes are breaking backward compatibility - for example:

`getOrCreateOrder($basename, $domains, $keyType = 'rsa', $notBefore = '', $notAfter = '')`

IMO `$keyType` will be used more often that notBefore and notAfter variables (since in most cases certs are generated for default period).

**Comment by yourivw** [comment]
Thanks for helping out with the library and I'm glad you like it. I haven't had time to look into ECDSA yet so feel free to help out. Please create a pull request.
Regarding the `$keyType`, I completely agree. `$notBefore` and `$notAfter` were added to give the user this option but aren't very significant.

**Comment by yourivw** [comment]
The PR is now merged into the new master branch. The old version is maintained as v1.0.0 to give some support to lower PHP versions as well, but will not be maintained.
I did alter the code a little to keep it in the same style.
