### ISSUE TITLE
Where are the certs and how to install them??

### ISSUE THREAD

**Issue by nomaam** [yourivw/LEClient#102]
This is probably a very silly question, but I got the code to work and it states certification for 'mysite.com' saved. Where is it saved? How do I install it on my shared hosting plan? From what I can see there is a SSL folder with sub folders 'certs', 'csrs' and 'keys'. Once I locate the files created by the script do I just modify the script to save them in that SSL folder and would the SSL certs now be installed?

**Comment by yourivw** [comment]
@nomaam 
My apologies, I don't have a lot of time anymore to work in this project. I am also not using it a lot anymore myself.
This is unfortunately a hosting specific question/issue, and not related to this library. You must have the option/right to do this on your specific hosting.
