### ISSUE TITLE
support for alternate certificate chain 

### ISSUE THREAD

**Issue by kansal15** [yourivw/LEClient#106]
Let's Encrypt is going to have "ISRG Root X1" certificate chain by default from Jan 11, 2021 [link](https://letsencrypt.org/2020/11/06/own-two-feet.html#if-you-are-a-site-owner). If site admin wants to have "DST Root X3" certificate chain, then "ACME 'Alternate' Link Relation" feature/support will be required. 

Certbot version > 1.6.0 support this. 

Does we have this support in [LEClient](https://github.com/yourivw/LEClient) and if not, then any plan to incorporate this change.

**Comment by yourivw** [comment]
@kansal15 
My apologies, I don't have a lot of time anymore to work in this project. I am also not using it a lot anymore myself.
Support for alternative chain added through #105
