### ISSUE TITLE
Need an option to return data instead of storing them in a Folder.

### ISSUE THREAD

**Issue by ggedde** [yourivw/LEClient#107]
Thanks for this library!
I really appreciate all the work you did on this.

However, I can't use it as it forces storing the certs in a folder.
I need an option to just get the contents of the certs and allow me to store them how ever I need to.
My servers are created on the fly and removed as needed so I need to store the certs via DB or third party storage like S3, etc.

Sure I can just get the file contents after they have been created, but that wouldn't help me when I need to renew them as that server might be newly created and has no certs on its drive. Sure i can create the files right before I run the renew, but then I have to make sure to remove them, etc and that would be a lot of IO work that is not necessary.

Instead it would be nice to have an option to set 'storage' to false or something like that and instead 'getCertificate' and 'RSAGenerateKeys' returned the data instead of writing to disk.

Thanks

**Comment by Zwartpet** [comment]
I've refactored [lordelph's fork](https://github.com/lordelph/php-certificate-toolbox) to make it composer installable, this has the option to create your own storage classes to save stuff elsewhere -> https://github.com/Zwartpet/php-certificate-toolbox

**Comment by yourivw** [comment]
@ggedde 
My apologies, I don't have a lot of time anymore to work in this project. I am also not using it a lot anymore myself.
I'm not currently extending this project, so hopefully the mentioned fork could help you out.
