### ISSUE TITLE
Missing 'name' in composer.json and missing release

### ISSUE THREAD

**Issue by czirkoszoltan** [yourivw/LEClient#18]
To make the `composer.json` file usable, the following changes have to be made:
1. Add these three lines to `composer.json`:
```
    "name": "yourivw/LEClient",
    "type": "library",
    "description": "PHP LetsEncrypt client library for ACME v2",
```
2. Create a release numbered 1.1.0 on github (as that is referenced in the example).

After that, people using your library can create a `composer.json` file like this:
```
{
    "repositories": [
        {
            "url": "https://github.com/yourivw/LEClient.git",
            "type": "git"
        }
    ],
    "require": {
        "yourivw/LEClient": "^1.1.0"
    }
}
```
and then do a `composer update` and a `composer install`.

**Comment by yourivw** [comment]
So just to be sure, the combined composer.json file looks as follows? I'm not working with composer often.

```
{
    "name": "yourivw/LEClient",
    "type": "library",
    "description": "PHP LetsEncrypt client library for ACME v2",
    "repositories": [
        {
            "url": "https://github.com/yourivw/LEClient.git",
            "type": "git"
        }
    ],
    "require": {
        "yourivw/LEClient": "^1.1.0"
    }
}
```

**Comment by czirkoszoltan** [comment]
Yes, I guess so. I tried it with my fork of the project and it worked, but I'm not a power user of composer either.

**Comment by harikt** [comment]
You don't need the library name itself in the `require` . 


```
{
    "name": "yourivw/LEClient",
    "type": "library",
    "description": "PHP LetsEncrypt client library for ACME v2",
    "require": {
        "php": "^5.X || ^7.0",
    }
}
```

Change 5.X version that is supported. And now you can tag releases. People can then download appropraite versions. So any change in master will not effect the already installed version. ( ie they don't want to use dev-master which is harmful ) . I can help you with what I know about composer. Let me know if that helps.

Thank you.

**Comment by LoranRendel** [comment]
Please also register package on packagist,

**Comment by yourivw** [comment]
Updated the composer.json and registered on packagist under yourivw/leclient.
