### ISSUE TITLE
DNS caching

### ISSUE THREAD

**Issue by LoranRendel** [yourivw/LEClient#20]
DNS caching cause errors like `DNS challenge for 'domain.zone' tested, found invalid.`
There must be some way to ignore DNS cache or avoid local checks.

**Comment by GXTX** [comment]
There isn't a way.

**Comment by LoranRendel** [comment]
I know that i add some data to DNS and can check it is correct, but *local* DNS test failed.
As I get it there is no LE validate challenge request made in this case.

**Comment by jetsam729** [comment]
1) set **TTL** of records to 60-**90**s (most of dns hosting start from **90**s) and **sleep**(some s) into setDNSRecord() funct.
2) if used local dns (like named/deadwood)  - reload before start (+ in win ipconfig /flushdns)

**Comment by yourivw** [comment]
I couldn't this problem by myself. A changed DNS record is correctly retrieved by my system. Nevertheless I made an option to bypass the local verification, please see the notes in [release 1.1.1](https://github.com/yourivw/LEClient/releases/tag/1.1.1) and the master branch.
