### ISSUE TITLE
Renewal Of Certificates

### ISSUE THREAD

**Issue by stephenbaugh** [yourivw/LEClient#22]
Hello

First, thank you for the awesome and easy to use client. Most appreciated.

I am sorry, I am not sure if I have missed something obvious, but how does one renew certificates using this client. Do they just come back as pending and the next certificate creation present them to the client for revalidation or something different. Of do I need to run the script again with each domain?

Thanks
Stephen

**Comment by yourivw** [comment]
As far as I know, the renewal is done by LetsEncrypt when an order is created from the same account with the same domains. When the domain names in the request have changed, a new certificate is issued.

**Comment by mniehren** [comment]
Hi,

i successfully create an certificate yesterday and try to renew it today. I try it the
same way, i've done yesterday for creation. But i don't got back a new certificate.
Only the yesterday created one.

So, as Stephen, i don't know how to handle the renew ...

best regards
  Michael

**Comment by yourivw** [comment]
Correct me if I'm wrong, but I believe LetsEncrypt returns the same certificate if nothing has changed in the SAN domain list and the certificate is created within a certain number of days. Unfortunately I'm not able to find this documented at this moment., but I believe I did read about it.
Can anyone confirm this?

**Comment by KnightAR** [comment]
If I'm not mistaking, the officially client states that a cert can't be renewed for at least the first 30 days. After the 30 day mark, a new cert can be generated.

**Comment by stephenbaugh** [comment]
Hi. As stated by yourivw and KnightAR if you re run the order request after 30 days (usually at 60 days) a renewed replacement cert will be issued.

Thanks

**Comment by prionkor** [comment]
Helpful! This ticket should be linked for documentation. :)

**Comment by ggedde** [comment]
@yourivw  I would recommend that you add a section to the README explaining this and title it as "Renewing Certificates"
