### ISSUE TITLE
Fake LE Intermediate X1

### ISSUE THREAD

**Issue by sq4** [yourivw/LEClient#24]
Hi, 

First of all it's a very nice script. No Nonsense library's or updates just RUN and PLAY. 

However, 
When i get a certificate it's not working. Because it's signed / provided by "Fake LE Intermediate X1" this has to be "Let's Encrypt Authority X3" 

both challenges http and dns are giving the same fullchain.crt  

When i run the certbot script it works fine also with wild-card certificates . 
The fullchain.pem created by certbot is signed / provided by 'Let's Encrypt Authority X3'. 

But i dont like certbot :-) I like to use the PHP client. 

Kind Regards,
Rene

**Comment by GXTX** [comment]
That's happening because you're using the staging server. In your constructor you must set the second argument to false or set it to ```LEClient::LE_PRODUCTION```.

**Comment by sq4** [comment]
Hi, @GXTX,

!!! YESS !!! 

I changed: 
$client = new LEClient($email, **_true_**, LECLient::LOG_STATUS);

into:
$client = new LEClient($email, **_LEClient::LE_PRODUCTION_**, LECLient::LOG_STATUS);

and the Certificate is signed/provided by "Let's Encrypt Authority X3"

:100: Points for you,
Thank you very very Much. 

Kind Regards,
René

**Comment by zhrtc** [comment]
But I still continuously getting Fake LE Intermediate X1 cert after I made the following changes!
`public function __construct($email, $acmeURL = LEClient::LE_PRODUCTION, $log = LEClient::LOG_DEBUG, $certificateKeys = 'keys/', $accountKeys = '__account/')`
Very weird!

**Comment by GXTX** [comment]
@zhrtc revert back to what it was, I didn't mean edit LEClient's files. Read right above and it shows what I actually meant. :)

**Comment by yourivw** [comment]
The default URL has been set to the production environment in [release 1.1.1](https://github.com/yourivw/LEClient/releases/tag/1.1.1) and the master branch.

Is this problem resolved?

**Comment by zhrtc** [comment]
@GXTX Thanks. Finally I found it is because the settings in the sample instead of the LEClient's file.

**Comment by GXTX** [comment]
@yourivw that seems like a bad idea, having it pre-set to production.

**Comment by yourivw** [comment]
@GXTX well I designed it for production, so in my mind that should be the default setting. The only reason I initially only set it to staging while that was the only server available.
Of course one can use the staging server if preferred.

**Comment by GXTX** [comment]
I'd still think it'd be better for the user to understand how the lib works before setting prod. btw this issue should be closed. :) thanks for your work.

As a side note I experienced some really weird action by ```LEFunctions::checkDNSChallenge()```, I had a loop to check it until it passed then I'd run ```LEOrder::verifyPendingOrderAuthorization``` and it'd fail the check.

**Comment by yourivw** [comment]
@GXTX I appreciate your input.

I've read some more input on the checkDNSChallenge. I cannot find any issues with it myself, but I created the option to bypass the local verification in version 1.1.1
See #20 as well for this.

Closing this issue now.

**Comment by viharm** [comment]
> 
> 
> @GXTX well I designed it for production, so in my mind that should be the default setting. The only reason I initially only set it to staging while that was the only server available.
> Of course one can use the staging server if preferred.

Since this library is not primarily targetted end users, but at app developers or savvy users,  I recommend setting the default as staging server, but it's not a big deal. App developers need to be alert enough to choose the right option.
