### ISSUE TITLE
Unable to install via composer

### ISSUE THREAD

**Issue by GXTX** [yourivw/LEClient#29]
```yourivw/leclient 1.1.1 requires php ^5.2 -> your PHP version (7.2.3) does not satisfy that requirement.```

From my limited knowledge of composer I believe this should work properly. However I think you should force the use of PHP7+ as PHP 5.6 will stop getting security updates at the end of the year.

```
"require": {
    "php": ">=5.2",
}
```

Interestingly enough I can't even get it to properly install and get picked up via autoload with ```--ignore-platform-reqs```, which I think might be from the location of LEClient.

**Comment by yourivw** [comment]
You're right, I changed it in the master branch and I'll push it into the next release.
