### ISSUE TITLE
Certificate renewal

### ISSUE THREAD

**Issue by meteortech** [yourivw/LEClient#42]
I must be doing something wrong and would like some clarification on certificate renewal.  
I am using DNS verification and when I went to renew the certificate I received new dns entries for the domains being renewed.  The certificate being ordered was unchanged from the last time and was the first renewal of an original certificate.  

I had removed the directory created by LEClient for the previous order before creating this order.  The certificate was being renewed about 62 days after the original, so was in the window that is expected to renew without a new validation.  Any ideas on how to correct for next time??

**Comment by danb35** [comment]
If you're renewing 60 days after issuance, you will need a new validation--IIRC, validations are only good for 7 days.
