### ISSUE TITLE
PHP Notice:  Undefined index: agreement in /var/www/composer/vendor/yourivw/leclient/LEClient/src/LEAccount.php on line 129

### ISSUE THREAD

**Issue by roncemer** [yourivw/LEClient#43]
When you create an order for a new domain, you get this notice:
PHP Notice:  Undefined index: agreement in /var/www/composer/vendor/yourivw/leclient/LEClient/src/LEAccount.php on line 129

To fix, please use array_key_exists() to avoid referencing the 'agreement' key when it doesn't exist.

Line 129.  Change this:
    $this->agreement = $post['body']['agreement'];
to this:
    $this->agreement = array_key_exists('agreement', $post['body']) ? $post['body']['agreement'] : '';

I had seen it doing the same with some other attributes in that same block of code.  Probably best to do it for all of the attributes, and don't assume that any particular attribute is present in the body.

When fixed, please issue a new release and push it to composer so we can update using composer.

Thanks!

**Comment by yourivw** [comment]
Should have been resolved by merging pull requests, now released in [v1.1.3](https://github.com/yourivw/LEClient/releases/tag/1.1.3).
