### ISSUE TITLE
Error on Renew

### ISSUE THREAD

**Issue by Doccos** [yourivw/LEClient#44]
I tried to Renew the Certificate but i got an error:

`Fatal error: Uncaught RuntimeException: Invalid response, headers: HTTP/1.1 404 Not Found Server: nginx Content-Type: application/problem+json Content-Length: 106 Expires: Fri, 10 Aug 2018 12:25:11 GMT Cache-Control: max-age=0, no-cache, no-store Pragma: no-cache Date: Fri, 10 Aug 2018 12:25:11 GMT Connection: keep-alive in /var/www/web2240/html/letsencrypt.domain.at/LEClient/src/LEConnector.php:146 Stack trace: #0 /var/www/web2240/html/letsencrypt.domain.at/LEClient/src/LEConnector.php(170): LEConnector->request('GET', 'https://acme-v0...') #1 /var/www/web2240/html/letsencrypt.domain.at/LEClient/src/LEAuthorization.php(62): LEConnector->get('https://acme-v0...') #2 /var/www/web2240/html/letsencrypt.domain.at/LEClient/src/LEOrder.php(261): LEAuthorization->__construct(Object(LEConnector), 1, 'https://acme-v0...') #3 /var/www/web2240/html/letsencrypt.domain.at/LEClient/src/LEOrder.php(130): LEOrder->updateAuthorizations() #4 /var/www/web2240/html/ in /var/www/web2240/html/letsencrypt.domain.at/LEClient/src/LEConnector.php on line 146`

The body of the response was:
`{ "status": "invalid", "expires": "2018-06-01T12:30:35Z", "identifiers": [ { "type": "dns", "value": "*.domain.at" }, { "type": "dns", "value": "domain.at" } ], "authorizations": [ "https://acme-v02.api.letsencrypt.org/acme/authz/r-em1tNAfuYrrcvdHQzy85hE-63F1QQrLdhyVh6boLU", "https://acme-v02.api.letsencrypt.org/acme/authz/zI6AuJt46C_YYa99mqOMZzj-9LjIC5cXGE15J08CePk" ], "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/35550320/6608957" }{ "type": "urn:ietf:params:acme:error:malformed", "detail": "Expired authorization", "status": 404 }`

**Comment by yourivw** [comment]
Did you create new authorizations? In the response it seems that you try to renew with expired authorizations.

**Comment by LoranRendel** [comment]
i just have encountered the same problem.

It happens if there is an order file with expired URL.

The order URL response:
```js
{
  "status": "invalid",
  "expires": "2018-06-11T06:57:29Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "example.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/...",
    "https://acme-v02.api.letsencrypt.org/acme/authz/..."
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/..."
}
```

LeOrder.php:108
```php
$get = $this->connector->get($this->orderURL);
if(strpos($get['header'], "200 OK") !== false)
```

Actually LE server returns `200` with `"status": "invalid"`.

The correct code must be:
```php
$get = $this->connector->get($this->orderURL);
if(strpos($get['header'], "200 OK") !== false && $get['body']['status'] != "invalid")
```

In this case we get correct behavior instead of exception:
```
13-09-2018 15:12:42, function LEClient __construct:
LEClient finished constructing

13-09-2018 15:12:42, function LEOrder __construct:
Order data for 'example.com' invalid. Deleting order data and creating new order.

13-09-2018 15:12:44, function createOrder (function LEOrder __construct):
Created order for 'example.com'.

13-09-2018 15:13:51, function finalizeOrder:
Order for 'example.com' finalized.

13-09-2018 15:13:52, function getCertificate:
Certificate for 'example.com' saved

```
