### ISSUE TITLE
PHP Notice:  Undefined variable: config in /LEClient/src/LEFunctions.php on line 65,

### ISSUE THREAD

**Issue by chnypc** [yourivw/LEClient#47]
Hi,

When creating new account and certificate it's getting error as below.

[Wed Sep 19 10:55:57.571476 2018] [php7:notice] [pid 23053] [client 89.145.186.214:61850] PHP Notice:  Undefined variable: config in /var/www/public_html/LEClient/src/LEFunctions.php on line 65

Thanks,

**Comment by yourivw** [comment]
Fixed in #54 and version 1.1.5 released with the fix.
