### ISSUE TITLE
Incorrect folder for certificate and fullchain_certificate 

### ISSUE THREAD

**Issue by bilogic** [yourivw/LEClient#57]
The files ```certificate.crt``` and ```fullchain.crt``` are not being saved in the ```$basename``` folder as documented here 
https://github.com/yourivw/LEClient/blob/a9ce9f2c133a379d4a7137d80ed5881e50a7bdf8/examples/dns_init.php#L20

Instead, they are directly saved as ```keys/certificate.crt``` and ```keys/fullchain.crt```. It will overwrite earlier ones when creating multiple certs.

**Comment by willvin313** [comment]
@bilogic true, but you can correct it for yourself by providing the path
example:
```
$basename = "example.org";

// the forth('keys/'.$basename.'/') parameter is what you need when initializing the leclient.
$client = new LEClient($email, true, LECLient::LOG_DEBUG, 'keys/'.$basename.'/');
```

**Comment by bilogic** [comment]
I see, did not realize that. Nonetheless, it would be good if the author can fix this for everyone.

Thanks.
