### ISSUE TITLE
Uncaught RuntimeException: Invalid response, header: HTTP/1.1 200 OK

### ISSUE THREAD

**Issue by arsonus** [yourivw/LEClient#61]
Great job taking your time to craft this library.

I encountered an error and after some digging, it turns out Let's Encrypt has made changes to HTTP Status Code for HEAD new-nonce.

More Info:
-------
https://community.letsencrypt.org/t/acme-v2-change-to-http-status-code-for-head-new-nonce/82000

Fix:
---------
File: https://github.com/yourivw/LEClient/blob/master/src/LEConnector.php#L91
Change to:
		`if(strpos($this->head($this->newNonce)['header'], "200 OK") == false) throw new \RuntimeException('No new nonce.');`

File: https://github.com/yourivw/LEClient/blob/master/src/LEConnector.php#L145
Change to:

`if(	(($method == 'POST' OR $method == 'GET') AND strpos($header, "200 OK") === false AND strpos($header, "201 Created") === false) OR
			($method == 'HEAD' AND strpos($header, "200 OK") === false))
		{
			throw new \RuntimeException('Invalid response, header: ' . $header);
		}`

Heads Up!

**Comment by mbardelmeijer** [comment]
Is PRed (https://github.com/yourivw/LEClient/pull/60), can this be merged?

**Comment by bezumkin** [comment]
Works for me, please update this pretty useful library!

**Comment by viharm** [comment]
This works for me too. Awaiting update.

**Comment by vaaguirre** [comment]
This is the best acme library is found. Can this fix be merged please? 

I realize its been a while since the last activity here, can someone fork and add this fix?

**Comment by yourivw** [comment]
Issue has been fixed/merged and version 1.1.5 released with the fix.
