### ISSUE TITLE
LetsEncrypt changed their Production CDN, LEClient doesn't work anymore

### ISSUE THREAD

**Issue by sagarspatil** [yourivw/LEClient#77]
More details about CDN here - https://community.letsencrypt.org/t/new-cdn-for-the-production-api/102629

**Comment by a3dho3yn** [comment]
#76 fixes this issue

**Comment by sagarspatil** [comment]
@a3dho3yn yes sir, I owe you a beer :)

**Comment by yourivw** [comment]
Unfortunately I was not able to go online and fix this earlier. Now fixed in release [1.1.10](https://github.com/yourivw/LEClient/releases/tag/1.1.10). Thanks for the fix!

**Comment by EtienneBruines** [comment]
@yourivw You might want to close this issue
