### ISSUE TITLE
Unexpected exception occurred: Invalid response, header: HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by youwebtw** [yourivw/LEClient#79]
Today, when I initialize a new order  it will occur the following error, how to fix it? I have update to the latest version but it is still occurred.

```
Server: nginx
Date: Tue, 05 Nov 2019 02:56:41 GMT
Content-Type: application/problem+json
Content-Length: 110
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
```

**Comment by dragonattack** [comment]
same here
> yourivw/leclient 1.1.10

**Comment by dragonattack** [comment]
I solved my problem. I tried to renew cert and there was outdated `order` file from last time.
Delete `/keys/domain.com/order` file and it will get new order id.

**Comment by youwebtw** [comment]
It is works.

> I solved my problem. I tried to renew cert and there was outdated `order` file from last time.
> Delete `/keys/domain.com/order` file and it will get new order id.

**Comment by nblom** [comment]
Same issue here, a patch that deletes the order file if 404 would be great

**Comment by ttodua** [comment]
setting the `true` to `false` fixed for me:

`
$client = new LEClient($email,   **false**,   LECLient::LOG_STATUS);
`
