### ISSUE TITLE
Fatal error:  Uncaught Error: Class 'LEClient\Exception' not found

### ISSUE THREAD

**Issue by LoranRendel** [yourivw/LEClient#86]
`Fatal error:  Uncaught Error: Class 'LEClient\Exception' not found in /vendor/yourivw/leclient/src/LEFunctions.php:175`

**Comment by yourivw** [comment]
Thank you, apparently not tested well enough. I will release version 1.2.1 soon (today) to fix this issue.

**Comment by yourivw** [comment]
Should be resolved now in [version 1.2.1](https://github.com/yourivw/LEClient/releases/tag/1.2.1)
