### ISSUE TITLE
Is this line mistyped or so? its throwing some error

### ISSUE THREAD

**Issue by gowebsmarty** [yourivw/LEClient#88]
https://github.com/yourivw/LEClient/blob/7c54c2be2ea668ce88bc3209f07dbe826fc4455d/src/Exceptions/LEException.php#L48

**Comment by yourivw** [comment]
Why do you think it's a typo? What error is it throwing? Please elaborate.

**Comment by gowebsmarty** [comment]
I noticed an error saying unexpected '?' or so

Is this part valid / is it any shorthand operator? - **: ?array** 

Shouldn't it be { after function()

**Comment by yourivw** [comment]
The ? is part of the return type hint. It says that it returns an array, the question mark says it can also return null.

I didn't notice this is only added in PHP 7.1, while the library still supports PHP 5.2. Are you using a PHP version older than 7.1?
I will change this when I have the opportunity.

**Comment by gowebsmarty** [comment]
Yes. Noticed it on older php :)

**Comment by yourivw** [comment]
Fixed for PHP 5 now in [version 1.2.2](https://github.com/yourivw/LEClient/releases/tag/1.2.2).
