### ISSUE TITLE
Support for externalAccountBinding?

### ISSUE THREAD

**Issue by ghost** [yourivw/LEClient#96]
May I ask if there is any plan to support [externalAccountBinding](https://tools.ietf.org/html/rfc8555#section-7.3.4)?

Thanks

**Comment by yourivw** [comment]
As far as I know and can find, LetsEncrypt is not accepting or planning to implement externalAccountBinding. Since this library is specifically targeting LetsEncrypt, I am therefore not planning to support that as this moment.
