### ISSUE TITLE
Get identifiers of valid authorizations

### ISSUE THREAD

**Issue by bilogic** [yourivw/LEClient#98]
Hi,

Possible to add a ```getValidAuthorizations()``` so that ```$auth->identifier['value']``` can be retrieved to remove the DNS entries?
Sometimes, the DNS verification process fails at different points and needs to resume.

**Comment by yourivw** [comment]
@bilogic 
My apologies, I don't have a lot of time anymore to work in this project. I am also not using it a lot anymore myself.
Functions are now added in the new release through #99
